name: bright_me
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  action_slider: ^0.7.0
  another_stepper: ^1.2.2
  bloc: ^8.1.2
  calendar_date_picker2: ^0.5.3
  camera: ^0.10.5+5
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_bubble: ^2.0.2
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.2
  flutter_slidable: ^3.0.0
  flutter_switch: ^0.3.2
  form_validator: ^2.1.1
  get_storage: ^2.1.1
  grouped_list: ^5.1.2
  image_picker: ^1.0.4
  otp_text_field: ^1.1.3
  path_provider: ^2.1.1
  styled_text: ^8.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#ffffff"

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#ffffff"

  web: false
  ios: false

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Black.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
